### PR TITLE
PR template

### PR DESCRIPTION
**Pull request by atherdon**

### CODE REVIEW

**Comment by atherdon** [comment]
please approve this pr - because i change the settings, so 0 prs can be merged at fetch without reviews - mine as well :)

**Comment by atherdon** [comment]
hmm, i see that you're reviewed it. but for some reasons github prevething it from merging ;(

**Comment by atherdon** [comment]
oh,, it actually works

**Comment by vadim9999** [comment]
WOW I doesn't using this feature "approve"

**Comment by atherdon** [comment]
just making our code process more cool as big companies do

>

**Pull request merged**
