### PR TITLE
updated UnitConversion/files.test.js

### PR DESCRIPTION
**Pull request by Beni03**
Tests are added to check objects are not empty

### CODE REVIEW

**Comment by atherdon** [comment]
not sure - is these file are generated version, right? just a bit confused, Vadim, please take a look

**Comment by atherdon** [comment]
by quick view - looks fine, nice work Benitha, i think we can move something more complex on your shoulders than

**Comment by vadim9999** [comment]
Yes it's not a generated version

**Comment by atherdon** [comment]
I'm a Wizard

xxx

**Pull request merged**
