### PR TITLE
created separate file (methods.js) with methods from index.js

### PR DESCRIPTION
**Pull request by vadim9999**

### CODE REVIEW

**Comment by atherdon** [comment]
i mean as you can see - our test system failed checks, so it should be solved too

**Comment by atherdon** [comment]
#20

**Comment by vadim9999** [comment]
@atherdon how can I see log or something of failed check? Why doesn't work this code?

**Comment by atherdon** [comment]
https://www.useloom.com/share/fb213015e5a044ad9150c5aff8649c0f

**Comment by vadim9999** [comment]
@atherdon how to know what code line doesn't work?  Or need I install node.js and deploy this project to know where is the problem.

**Comment by atherdon** [comment]
if you want - you can install nodejs, for sure, but my point to figure out
it without setting up a node server for now.
But if you want to install nodejs i'm ok with it - because it'll simplify
our workflow, but you'll need to learn how to use nodejs. tell me what do
you think is better. we also can use some online services like Glitch, that
will create a nodeserver online, so you'll not need to worry about learning
how it works


On 13-Jul-2018 at 08:46 PM, Vadim wrote:


@atherdon <https://github.com/atherdon> how to know what code line doesn't
work? Or need I install node.js and deploy this project to know where is
the problem.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/pull/24#issuecomment-404949528>,
or mute the thread

**Pull request merged**
