### PR TITLE
Replaced all parser() method with __get() method in all projects

### PR DESCRIPTION
**Pull request by wahaj-47**

### CODE REVIEW

**Comment by atherdon** [comment]
Ok, this part is done as it needed

**Comment by wahaj-47** [comment]
I don’t really see how this is good for the project. Can you explain it to me ?

**Comment by atherdon** [comment]
Yes, I'll explain to you a bit later. Please continue the same update at other files.
I'm pushing your changes to npm, in order to check how it works on our projects

**Comment by wahaj-47** [comment]
I already did that, replaced all the basic get functions.

**Pull request merged**
