### PR TITLE
Update data/Grocery/grocery.json

### PR DESCRIPTION
**Pull request by kraftaa**
added ingredients for department int the array with "id:1"

### CODE REVIEW

**Comment by atherdon** [comment]
Ok, after filming video - your fork is not synced. and it generate a merge conflict. i did with purpose - in order to teach you more about git/github workflows :) 

Details #149

and you'll need to submit new changes. right now your version are not correct(i assume you add ingredients to the main grocery.json file)

**Comment by atherdon** [comment]
i updated code - please fetch new version.
but you still need to update number of items in arrays at tests in order to prevent tests from crashing

**Comment by atherdon** [comment]
@kraftaa can you specify what file you're used and what number of grocery lists was moved right now? we made big number of changes with this repo, and i want to mergre your changes, but don't understand totally how much work was done. thanks in advance

**Comment by atherdon** [comment]
ok, build works fine - thank you!

**Comment by kraftaa** [comment]
Hi Arthur,
thank you so much for waiting!
I've finished both R & Python Wrangling projects, they were time sensitive and I'm back now :)

so,
what I have now:

I've synced my fork and committed to my fork ingredient files and updated department lists.
I did all four `md` files, with exception:

1. what to do with the last ingredients in `4.md` like:

```
BUILDING A HEALTHY VEGAN GROCERY LIST
http://www.ilovevegan.com/resources/building-a-healthy-vegan-grocery-list/

FRUITS
  FRESH
    Apples
    Pears
    Kiwis
```
so here we have nested departments and I don't know how to handle it in our data.
and how to put it into `grocery.json`
what to put into `departments`
```
    {
    "departments": [
      "Other"
    ],
    "id": 26,
    "name": "building-a-healthy-vegan-grocery-list",
    "img": false,
    "desc": false,
    "slug": false
  },
```

2. in `1.md` I've asked it but I think it was lost in conversation, we have such `meal plan`

```
meal calendar
Breakfast

Oatmeal with Dried Fruit, Flax Meal, and Cinnamon
Lunch

Pasta la Caprese
Green Smoothie
Dinner

Split Pea Soup
One piece of Whole Wheat Garlic Bread
Mixed Greens Salad with Balsamic Vinaigrette
Snacks

Apple with Almond Butter (or other nut butter)


Day Two
Breakfast

High-fiber, Low-Sugar Cereal with Almond Milk and Banana
Lunch
```
what is the structure here?

thank you!

PS Meanwhile I'm re-reading links you've sent me, thank you for the information!

**Comment by atherdon** [comment]
hold on few minutes - publishing our changes to npm and upgrading our
projects.
Will reply after that

**Comment by atherdon** [comment]
Not a problem at all and happy to have you back!
Before I'll dig into your questions I need to ask you few things.

Btw, it's actually a good time - with this plugin we're at crossroads right now, so maybe you should join our discussion about what and how we should move forward. I'm conflicted and cannot make a choice right now, so in last few days I'm gathering all information into one place

---

I know that you have skills at Frontend and Python/ML side. And i'm not sure if this module with tasks that we have are an interesting thing for you to do. Tell me if i'm wrong. 
Maybe i can also share with you information about tasks in other topics too? or now it's better to work on `fetch` plugin only? please advice

**Comment by kraftaa** [comment]
Hi Arthur, thank you, 
I haven't got experience in Python backend yet. In ML & Python I can do wrangling data (like gathering/parsing them from sites/databases, cleaning,combining+ data analysis, I'm going to learn backend later.

Sorry don't understand the question about 'fetch` I think I kind of lost in what going on now, reading issues' list

**Comment by atherdon** [comment]
just find some time to re-read whole our conversation and proceed it.
- Ok, understand about your skills, that outside js. I assume we should continue to work on this plugin and decide to move forward later. But will keep you in mind for our next ML projects...
- Yes, please review tasks at this repo, I actually assigned a few of them to you, so it can be easy to filter.
- We also have a pending discussion about what major updates we need to do with this plugin



About Meal calendar - don't worry about it. One website has grocery list + meal calendar and i decided to put it here. yesterday i move that content into separated json file, that we have in `Mealcalendar` folder. [link](https://github.com/GroceriStar/groceristar-fetch/blob/master/data/MealCalendar/First-Vegan-Grocery-List-MC.json) I assume this question solved.

About your second question. I save it, but we'll think about it later. Briefly - we need to discuss updates in our database structure, and i assume that this question will be solved after that. I add it to #184 in order to keep everything in one place

**Comment by kraftaa** [comment]
HI Arthur, thank you,
I'm reading it now.
about our database. I've seen one website which has logic  I think we better have:
there are few different filters and based on them you get your result (it's about dogs, but it doesn't matter it's the same principle).
I still think we need to have one database with different tables connected via keys and then we could easily choose protein or vegan or cheap or fast or snack or whatever
Filters are on the left side:

https://www.akc.org/dog-breeds/

**Comment by atherdon** [comment]
@kraftaa 100% agree with you. we're building this "one database" right now. as we have a modular approach - we decided to test small parts of the project, instead of building one big "website". For sure we'll have a big database, but before going big - we are solving small problems. if you think that you want more details or work at biggest task on this project - i can make it - it's not a problem.

**Comment by atherdon** [comment]
Btw, let's continue our conversation at some open tasks, that we have - here we have a very long tread that is hard to manage for me

**Pull request merged**
