### PR TITLE
clean up and changed variables

### LINKED ISSUE #51: clean up index.js + add chickenkyiv there too

### LINKED ISSUE #53: make all variables to have a similar plural
like diets, allergies, holidays, courses, cuisines
or diet, allergy, holiday, course, cuisine

### PR DESCRIPTION
**Pull request by vadim9999**
Fixes #51 , fixes #53

### CODE REVIEW

**Comment by atherdon** [comment]
did you update the same things at readme?

**Comment by vadim9999** [comment]
yes, I have changed variables name in readme, but should I change methods name?

**Comment by atherdon** [comment]
@vadim9999 if it will keep up to date Readme - then yes.
main goal of readme is to share it with other developers.
So they can easily understand what we're doing here

**Comment by atherdon** [comment]
ok, mergin it

**Comment by atherdon** [comment]
i think i got your question. it's upon you. right now it's not important.
so if you want - you can change it @vadim9999


On 30-Jul-2018 at 07:33 PM, Vadim wrote:


yes, I have changed variables name in readme, but should I change methods
name?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/groceristar-fetch/pull/57#issuecomment-408983184>,
or mute the thread

**Pull request merged**
