### PR TITLE
[Work in Progress] Implement and pass tests for Meal Calendar

### PR DESCRIPTION
**Pull request by Seenivasanseeni**
This PR is based out of projects-v2(4c8e514f3a18865a83095644843afaef1f593376) and this is to implement MealCalendar project and pass the jest tests. Don't merge this branch untill work is done.

### CODE REVIEW

**Comment by atherdon** [comment]
_tell me if you stuck_

**Comment by atherdon** [comment]
i hope you don't give up on doing this thing

**Comment by Seenivasanseeni** [comment]
Nope. I will resume working today

**Comment by Seenivasanseeni** [comment]
@atherdon I am still getting the error `  Plugin/Preset files are not allowed to export
 objects, only functions.`

**Comment by Seenivasanseeni** [comment]
I think i fixed the problem by having a file named `.babelrc` with contents
```{
    "presets": ['@babel/preset-env']
}```

**Comment by Seenivasanseeni** [comment]
@atherdon What is the use of sd-wrapper?

**Comment by Seenivasanseeni** [comment]
@atherdon I noticed few ambiguous code snippets in our project.  There are many instances where mealCalendar(through import and export) variable is used in many ways?

**Comment by Seenivasanseeni** [comment]
@atherdon  take a look at this.

**Comment by Seenivasanseeni** [comment]
sure @vadim9999

**Comment by Seenivasanseeni** [comment]
I will close this PR and start fresh.

**Pull request closed without merging**
