### PR TITLE
[RP] Initial Contributing version

### PR DESCRIPTION
**Pull request by Seenivasanseeni**
This PR is to add Contributing guidelines and development setup. Issue #437

### CODE REVIEW

**Comment by atherdon** [comment]
i assume your branch was fetched from projects2.0 branch?
just not sure if we should pay  attention to codeclimate errors or travis ci crashes....

**Comment by Seenivasanseeni** [comment]
I deleted that branch and PR. This branch is out of master.

**Comment by Seenivasanseeni** [comment]
@atherdon @vadim9999  can you take a look at this.

**Comment by atherdon** [comment]
i'm ok with that changes, just let's wait when Vadim will have time

>

**Pull request merged**
