### PR TITLE
fix

### PR DESCRIPTION
**Pull request by vadim9999**

### CODE REVIEW

**Comment by atherdon** [comment]
should we publish this version or it's not necessary now?

**Comment by atherdon** [comment]
ok, merging

**Comment by vadim9999** [comment]
>I can merge it, but have question: i have some commetns/adjustments, related to getKeyArray method. should i share them with you right now, while you working on it?

Yes

**Comment by atherdon** [comment]
updating package at react-shopping-list right now...

**Comment by atherdon** [comment]
or if you have another change - then i'll publish it again - no prob

**Comment by atherdon** [comment]
i upgraded  plugin at react-shopping-list

**Comment by atherdon** [comment]
upgraded plugin and merged changes into shoplist-template. did we fix #176 ?

**Pull request merged**
