### PR TITLE
created constants for models

### PR DESCRIPTION
**Pull request by elnur004**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by elnur004** [comment]
@atherdon are these a correct way to create constants for models?

**Comment by atherdon** [comment]
We don't need to store here the whole models as it was before.
1) you can create a file models, where you can store all consts with names to the model. please have a prefix MODEL_* with that names
2) you can have an additional consts, that will represent only files inside of the model. 
Just names will be fine
aka ALLERGY_FIELD_NAME will work fine

**Comment by atherdon** [comment]
looks file, but please do the same thing for course model as well

**Comment by elnur004** [comment]
@atherdon how to create course model? need there create any method for course?

**Comment by elnur004** [comment]
also, should we create favorites, grocery and ingredients models?

**Comment by atherdon** [comment]
at your latest commit you delete a json code related to allergy table and
replace it with js file for allergy-model.
you also deleted course json code. i assume you need to create another
file, similar to allergy model constants and put there data about course
table.

I'm talking about this delete file:
https://github.com/GroceriStar/groceristar-fetch/pull/456/commits/8b835fa8400bcdc672c2224333b0ecf5de8b6ece#diff-4d55620a397bc275d16b3c6d8aa09c5c

yes, we need those models as well. feel free and do them as well

**Comment by elnur004** [comment]
@atherdon i don't mean about deleted JSON files. 
i mean there are some methods which we have created already(yesterday).
`allergy`, `favorites`, `grocery` and `ingredients`.
also, there exist `const-departments-example.js`.
i want to know need we create models for these methods?
and the __page__  which you attached for using names on methods, there i couldn't see about course method.
and finally where exist the data about course
table?

**Comment by atherdon** [comment]
there a lot of questions and it's pretty late.

>  want to know need we create models for these methods

Yes, please do that

for next thing i'll reply tomorrow

**Comment by elnur004** [comment]
ok. i'll try to do.
i have fatigued you with a lot of questions :)

**Comment by atherdon** [comment]
yeah, I'm scared with them and running out from my Gmail ;)

>

**Comment by elnur004** [comment]
@atherdon are these constants correct for methods?

**Comment by atherdon** [comment]
i think it works for now.
merging. later, when we'll cover most part of that my readme file - we'll think more about it.
I'm doing a pretty similar thing right now on paper :) and it covers a corner at my floor :) 

Please continue with the next thing that you want

**Comment by atherdon** [comment]
thanks for follow up - i partially forget about it

**Comment by elnur004** [comment]
@atherdon is there any task for me?

**Pull request merged**
