### PR TITLE
Update showcase.test.js

### PR DESCRIPTION
**Pull request by Edebo**
testing showcase method

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
is this pull request part of your previous pull requests, right?

**Comment by Edebo** [comment]
yes

**Comment by atherdon** [comment]
got it. can you link your PRs together  - because it'll help Vadim to
review your changes quickly.
Do you also need a next task, right or do you have other things to do?

>

**Comment by Edebo** [comment]
i want @vadim9999 to certified i have finished this task.if i have finished then i will need a new one else should know the yet to be completed part

**Comment by atherdon** [comment]
got it

**Comment by atherdon** [comment]
got it

**Comment by atherdon** [comment]
please check this PR. right now it's conflicting with another PR that i merged just few minutes ago. or i need to rollover that PR and merge current one instead? Please elaborate @Edebo your prev PR - #382

**Comment by atherdon** [comment]
Ok, i think i figure it out. both of PRs are the same, mostly. i like this version, so i'm merging it

**Comment by Edebo** [comment]
ok

**Pull request merged**
