### PR TITLE
Created and updated play.js

### PR DESCRIPTION
**Pull request by Beni03**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to static food data?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] refactor
- [ ] documentation
- [ ] other

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

Are tests included?
- [ ] yes (*bugfixes and features will not be merged without tests*)
- [ ] no

Breaking Changes?
- [ ] yes (*breaking changes will not be merged unless absolutely necessary*)
- [ ] no

List any relevant issue numbers:

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Comment by atherdon** [comment]
@Beni03  I can merge this PR as well. The code looks fine. But for some reasons, I think you didn't run the `play.js` file and don't see the result of `console.log` in your command line. am I right? if yes - please make a small change at the project, in order to have the ability to run `play.js` script

**Comment by atherdon** [comment]
I'll give you a hint. check package.json and see how other similar scripts are calling. then share with me a screenshot of how our file running on your computer. Still cannot merge it right now

**Comment by Beni03** [comment]
for this code:

[image: image.png]

output:

[image: image.png]

Are you asking me to use stringify method to display JSON objects?

or for this code below,

[image: image.png]

Output is

[image: image.png]

**Comment by atherdon** [comment]
images didn't render. if you attach them via email - maybe it's better to upload via github website

**Pull request merged**
