### PR TITLE
Moved chickenKyiv methods to helper.js

### PR DESCRIPTION
**Pull request by wahaj-47**
Moved chickenKyiv methods to helper.js, passes test, doesn't crash

### CODE REVIEW

**Comment by wahaj-47** [comment]
But then duplicate functions will still be present in each project.

**Comment by atherdon** [comment]
The goal of helper file is to separate methods, that is not related to project modules.

**Comment by atherdon** [comment]
Ok, I can merge this pull request.
But can you apply _get to other `get` methods at chichenKyiv.js file as well?

**Comment by atherdon** [comment]
Ok, merging this changes. Please do the same thing at other `projects`

**Pull request merged**
