### PR TITLE
add getDepartmentsGraphQL

### PR DESCRIPTION
**Pull request by vadim9999**
Result
```
[ { department_id: 1,
    name: 'Fresh vegetables',
    desc: 'desc for department1',
    created_at: 1547668475013,
    updated_at: 1547668475013 },
  { department_id: 2,
    name: 'Condiments / sauces',
    desc: 'desc for department1',
    created_at: 1547668475013,
    updated_at: 1547668475013 },
  { department_id: 3,
    name: 'Dairy',
    desc: 'desc for department1',
    created_at: 1547668475013,
    updated_at: 1547668475013 },
  { department_id: 4,
    name: 'Cheese',
    desc: 'desc for department1',
    created_at: 1547668475013,
    updated_at: 1547668475013 },
....
]
```

### CODE REVIEW

**Comment by vadim9999** [comment]
in DB field id can be zero or it should be starts from 1?

**Comment by atherdon** [comment]
you can replace id with uuid:
```
const uuidv1       = require('uuid/v1');
id: uuidv1()
```

**Comment by vadim9999** [comment]
@atherdon but it's returns this 
```
43c5b78c-19ca-11e9-ba92-1de8759e63a0
```
The type of field id is Integer
```
department_id: Int!

```

**Comment by atherdon** [comment]
looks awesome - merging!

**Pull request merged**
